# autogenerated by __main__.py do not edit
top_level_module_names = ('QtCore', 'QtGui', 'QtWidgets', 'QtSvg')


def __getattr__(name):
    if name in top_level_module_names:
        import importlib
        return importlib.import_module('PySide6.' + name)
    raise AttributeError(name)
